#!/bin/sh
BOLD="\e[1m"
ITALIC="\e[3m"
BOLDRED="\e[1;31m"
BOLDGREEN="\e[1;32m"
ENDFORMAT="\e[0m"

echo "You are about to commit to branch${BOLD}" $(git branch --show-current)"${ENDFORMAT}\n"

while : ; do
    read -p "Are you sure about this? [Y/n] " RESPONSE < /dev/tty
    RESPONSE=${RESPONSE:-Y}
    if [ "${RESPONSE}" != "Y" ]
    then
	echo "\n${BOLD}Aborting commit!"
        exit 1
    else
	break;
    fi
done

echo "\n${BOLD}Step 1/3${ENDFORMAT}: Running linter..."
if ng lint
then
    echo "${BOLDGREEN}Linting is GOOD!${ENDFORMAT}"
else
    echo "${BOLDRED}ERROR! You should run ${ENDFORMAT}${ITALIC}yarn lint-fix${ENDFORMAT}${BOLDRED} and check your work before committing it!"
    exit 1
fi

echo "\n${BOLD}Step 2/3${ENDFORMAT}: Running unit tests...\n"
if yarn test 
then
    echo "\n${BOLDGREEN}Unit tests are GOOD!${ENDFORMAT}"
else
    echo "\n${BOLDRED}ERROR! You might wanna check how those unit tests are doing!"
    exit 1
fi
